# Generated by Django 3.1.7 on 2021-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_video_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='result',
            field=models.CharField(default='', max_length=255),
        ),
    ]
